### ISSUE TITLE
vila_live crushes

### ISSUE THREAD

**Issue by Shehjad-Ishan** [nvidia-holoscan/holohub#454]
I am trying to run vila_live inside docker container. Source is a loopback device. This error is occuring

```
>  ./run launch vila_live
> Default language for vila_live selected: cpp
> Run environment: export PYTHONPATH=${PYTHONPATH}:/../../../python/lib:/workspace/holohub/build/vila_live/python/lib:/workspace/holohub && export HOLOHUB_DATA_PATH=/workspace/holohub/data
> Run workdir: cd /workspace/holohub/build/vila_live
> Run command: bash -c '/workspace/holohub/applications/vila_live/run_vila_live.sh'
> Run command args: 
> [command] export PYTHONPATH=${PYTHONPATH}:/../../../python/lib:/workspace/holohub/build/vila_live/python/lib:/workspace/holohub && export HOLOHUB_DATA_PATH=/workspace/holohub/data
> [command] cd /workspace/holohub/build/vila_live
> [command] bash -c '/workspace/holohub/applications/vila_live/run_vila_live.sh'
> /usr/bin/python3: Error while finding module specification for 'tinychat.serve.model_worker_new' (ModuleNotFoundError: No module named 'tinychat')
> /usr/bin/python3: Error while finding module specification for 'tinychat.serve.controller' (ModuleNotFoundError: No module named 'tinychat')
> [info] [fragment.cpp:569] Loading extensions from configs...
> [info] [gxf_executor.cpp:249] [V4L2 to VLM app] Creating context
> [info] [gxf_executor.cpp:1912] Activating Graph...
> [info] [gxf_executor.cpp:1944] [V4L2 to VLM app] Running Graph...
> [info] [gxf_executor.cpp:1946] [V4L2 to VLM app] Waiting for completion...
> 2024-08-01 10:17:19.435 INFO  gxf/std/greedy_scheduler.cpp@191: Scheduling 4 entities
> [info] [context.cpp:50] _______________
> [info] [context.cpp:50] Vulkan Version:
> [info] [context.cpp:50]  - available:  1.3.204
> [info] [context.cpp:50]  - requesting: 1.2.0
> [info] [context.cpp:50] ______________________
> [info] [context.cpp:50] Used Instance Layers :
> [info] [context.cpp:50] 
> [info] [context.cpp:50] Used Instance Extensions :
> [info] [context.cpp:50] VK_EXT_debug_utils
> [info] [context.cpp:50] VK_KHR_external_memory_capabilities
> [info] [context.cpp:50] ____________________
> [info] [context.cpp:50] Compatible Devices :
> [info] [context.cpp:50] 0: NVIDIA RTX A2000 12GB
> [info] [context.cpp:50] Physical devices found : 
> [info] [context.cpp:50] 1
> [info] [context.cpp:50] ________________________
> [info] [context.cpp:50] Used Device Extensions :
> [info] [context.cpp:50] VK_KHR_external_memory
> [info] [context.cpp:50] VK_KHR_external_memory_fd
> [info] [context.cpp:50] VK_KHR_external_semaphore
> [info] [context.cpp:50] VK_KHR_external_semaphore_fd
> [info] [context.cpp:50] VK_KHR_push_descriptor
> [info] [context.cpp:50] VK_EXT_line_rasterization
> [info] [context.cpp:50] 
> [info] [vulkan_app.cpp:845] Using device 0: NVIDIA RTX A2000 12GB (UUID ef9478313962e02ed94bf73bd881b32f)
> -- starting webserver @ 0.0.0.0:8050
>  * Serving Flask app 'webserver'
>  * Debug mode: on
> WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
>  * Running on all addresses (0.0.0.0)
>  * Running on http://127.0.0.1:8050
>  * Running on http://192.168.0.101:8050
> Press CTRL+C to quit
> [info] [holoviz.cpp:1449] Input spec:
> - type: color
>   name: ""
>   opacity: 1.000000
>   priority: 0
> 
> [error] [gxf_wrapper.cpp:84] Exception occurred for operator: 'source' - Querying file descriptor timed out
> 2024-08-01 10:17:37.674 ERROR gxf/std/entity_executor.cpp@552: Failed to tick codelet source in entity: source code: GXF_FAILURE
> 2024-08-01 10:17:37.674 WARN  gxf/std/greedy_scheduler.cpp@243: Error while executing entity 7 named 'source': GXF_FAILURE
> 2024-08-01 10:17:37.730 INFO  gxf/std/greedy_scheduler.cpp@401: Scheduler finished.
> [error] [program.cpp:574] wait failed. Deactivating...
> [error] [runtime.cpp:1476] Graph wait failed with error: GXF_FAILURE
> [warning] [gxf_executor.cpp:1947] GXF call GxfGraphWait(context) in line 1947 of file /workspace/holoscan-sdk/src/core/executors/gxf/gxf_executor.cpp failed with 'GXF_FAILURE' (1)
> [info] [gxf_executor.cpp:1957] [V4L2 to VLM app] Graph execution finished.
> [error] [gxf_executor.cpp:1965] [V4L2 to VLM app] Graph execution error: GXF_FAILURE
> Traceback (most recent call last):
>   File "/workspace/holohub/applications/vila_live/vila_live.py", line 172, in <module>
>     main()
>   File "/workspace/holohub/applications/vila_live/vila_live.py", line 168, in main
>     app.run()
> RuntimeError: Querying file descriptor timed out
> [info] [gxf_executor.cpp:278] [V4L2 to VLM app] Destroying context
> [command] export PYTHONPATH=/opt/nvidia/holoscan/python/lib:/workspace/holohub/benchmarks/holoscan_flow_benchmarking && export HOLOHUB_DATA_PATH=""
> 
```

**Comment by Shehjad-Ishan** [comment]
I understood the problem. The loopback video was not running properly.

**Comment by Shehjad-Ishan** [comment]
> @Shehjad-Ishan is it working now?

Yes!

**Comment by Shehjad-Ishan** [comment]
> @Shehjad-Ishan is it working now?
