### ISSUE TITLE
llava.model.utils has no function named get_model_config

### ISSUE THREAD

**Issue by Shehjad-Ishan** [nvidia-holoscan/holohub#461]
I am running into this error
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/holohub/build/vila_live/tinychat/serve/model_worker_new.py", line 51, in <module>
    from tinychat.models.vila_llama import VilaLlamaForCausalLM
  File "/workspace/holohub/build/vila_live/tinychat/models/vila_llama.py", line 11, in <module>
    from llava.model.utils import get_model_config
ImportError: cannot import name 'get_model_config' from 'llava.model.utils' (/workspace/holohub/LLaVA/llava/model/utils.py)
```
I have checked llava.model.utils. get_model_config doesn't exist.

**Comment by NigelNelson** [comment]
Hey @Shehjad-Ishan, can you share the commands that were used to produce this stack trace?

**Comment by Shehjad-Ishan** [comment]
> Hey @Shehjad-Ishan, can you share the commands that were used to produce this stack trace?

Hey @NigelNelson I solved the problem. It was related to Llava repo rather than this repo. Now the application is running fine.
